export const UPDATE_TO_IMAGES = "UPDATE_TO_IMAGES";
export const REMOVE_FROM_IMAGES = "REMOVE_FROM_IMAGES";
export const ADD_TO_IMAGES = "ADD_TO_IMAGES";

export const RESET_ALL_IMAGES = "RESET_ALL_IMAGES";
export const INITIAL_IMAGES = "INITIAL_IMAGES";
